import { ROOM_SIZE } from '../constants/constant';
const ROOM_HALF = ROOM_SIZE / 2;

export const roomConfigs = [
    {
        id: 1,
        name: 'Classic Library',
        wallColor: 0x8B7355,
        floorColor: 0x4A3A2A,
        doorPosition: { x: 0, z: -ROOM_HALF + 0.1 },
        furniture: [
            { type: 'rug', position: { x: 0, y: 0, z: 0 }, size: 4 },
            { type: 'table', position: { x: -5, y: 0.5, z: 4 } },
            { type: 'table', position: { x: 5, y: 0.5, z: -4 } },
            { type: 'bookshelf', position: { x: ROOM_HALF - 0.4, y: 1, z: 4 } },
            { type: 'bookshelf', position: { x: -ROOM_HALF + 0.4, y: 1, z: -4 } },
            { type: 'bookshelf', position: { x: ROOM_HALF - 0.4, y: 1, z: -2 } },
            { type: 'chest', position: { x: 5, y: 0.3, z: 4 } },
            { type: 'pillar', position: { x: -6, y: 0.75, z: -6 } },
            { type: 'pillar', position: { x: 6, y: 0.75, z: 6 } },
            { type: 'vase', position: { x: -5, y: 0.65, z: 4 } },
            { type: 'vase', position: { x: 5, y: 0.65, z: -4 } },
            { type: 'lamp', position: { x: -3, y: 0, z: -3 } },
            { type: 'lamp', position: { x: 3, y: 0, z: 3 } },
            { type: 'statue', position: { x: 0, y: 0, z: 6 } },
            { type: 'plant', position: { x: -7, y: 0, z: 0 } },
            { type: 'plant', position: { x: 7, y: 0, z: 0 } },
            { type: 'painting', position: { x: -ROOM_HALF + 0.05, y: 2, z: 0 }, rotation: 0 },
            { type: 'painting', position: { x: ROOM_HALF - 0.05, y: 2, z: 0 }, rotation: Math.PI },
            { type: 'clock', position: { x: 0, y: 2.5, z: ROOM_HALF - 0.05 }, rotation: Math.PI }
        ]
    },
    {
        id: 2,
        name: 'Elegant Study',
        wallColor: 0x5A7A8F,
        floorColor: 0x3A4A5A,
        ceilingColor: 0xD0D8E0,
        doorPosition: { x: ROOM_HALF - 0.1, z: 0 },
        furniture: [
            { type: 'rug', position: { x: 0, y: 0, z: 0 }, size: 5 },
            { type: 'table', position: { x: -5, y: 0.5, z: -5 } },
            { type: 'table', position: { x: 5, y: 0.5, z: 5 } },
            { type: 'chair', position: { x: -5, y: 0.4, z: -4 } },
            { type: 'chair', position: { x: 5, y: 0.4, z: 4 } },
            { type: 'bookshelf', position: { x: -ROOM_HALF + 0.4, y: 1, z: 5 } },
            { type: 'bookshelf', position: { x: ROOM_HALF - 0.4, y: 1, z: -5 } },
            { type: 'chest', position: { x: -5, y: 0.3, z: 5 } },
            { type: 'chest', position: { x: 5, y: 0.3, z: -5 } },
            { type: 'pillar', position: { x: 6, y: 0.75, z: 6 } },
            { type: 'pillar', position: { x: 6, y: 0.75, z: -6 } },
            { type: 'pillar', position: { x: -6, y: 0.75, z: 6 } },
            { type: 'lamp', position: { x: -2, y: 0, z: -2 } },
            { type: 'lamp', position: { x: 2, y: 0, z: 2 } },
            { type: 'mirror', position: { x: -ROOM_HALF + 0.05, y: 1.5, z: 0 }, rotation: 0 },
            { type: 'statue', position: { x: 0, y: 0, z: -6 } },
            { type: 'plant', position: { x: 0, y: 0, z: 6 } },
            { type: 'painting', position: { x: 0, y: 2, z: -ROOM_HALF + 0.05 }, rotation: Math.PI },
            { type: 'painting', position: { x: 0, y: 2, z: ROOM_HALF - 0.05 }, rotation: 0 },
            { type: 'vase', position: { x: -5, y: 0.65, z: -5 } },
            { type: 'vase', position: { x: 5, y: 0.65, z: 5 } },
            { type: 'clock', position: { x: ROOM_HALF - 0.05, y: 2.5, z: 0 }, rotation: -Math.PI / 2 }
        ]
    },
    {
        id: 3,
        name: 'Royal Chamber',
        wallColor: 0x9F7A6B,
        floorColor: 0x6A4A3A,
        ceilingColor: 0xF0E8E0,
        doorPosition: { x: 0, z: ROOM_HALF - 0.1 },
        furniture: [
            { type: 'rug', position: { x: 0, y: 0, z: 0 }, size: 6 },
            { type: 'table', position: { x: 5, y: 0.5, z: -5 } },
            { type: 'table', position: { x: -5, y: 0.5, z: 5 } },
            { type: 'bookshelf', position: { x: ROOM_HALF - 0.4, y: 1, z: -5 } },
            { type: 'bookshelf', position: { x: -ROOM_HALF + 0.4, y: 1, z: 5 } },
            { type: 'chair', position: { x: 5, y: 0.4, z: -4 } },
            { type: 'chair', position: { x: -5, y: 0.4, z: 4 } },
            { type: 'chest', position: { x: 0, y: 0.3, z: -5 } },
            { type: 'pillar', position: { x: -6, y: 0.75, z: 6 } },
            { type: 'pillar', position: { x: 6, y: 0.75, z: -6 } },
            { type: 'pillar', position: { x: 0, y: 0.75, z: 0 } },
            { type: 'statue', position: { x: -7, y: 0, z: 0 } },
            { type: 'statue', position: { x: 7, y: 0, z: 0 } },
            { type: 'lamp', position: { x: -3, y: 0, z: 3 } },
            { type: 'lamp', position: { x: 3, y: 0, z: -3 } },
            { type: 'plant', position: { x: 0, y: 0, z: -6 } },
            { type: 'mirror', position: { x: ROOM_HALF - 0.05, y: 1.5, z: 0 }, rotation: -Math.PI / 2 },
            { type: 'vase', position: { x: 5, y: 0.65, z: -5 } },
            { type: 'vase', position: { x: -5, y: 0.65, z: 5 } },
            { type: 'painting', position: { x: ROOM_HALF - 0.05, y: 2, z: 0 }, rotation: -Math.PI / 2 },
            { type: 'painting', position: { x: -ROOM_HALF + 0.05, y: 2, z: 0 }, rotation: Math.PI / 2 },
            { type: 'clock', position: { x: 0, y: 2.5, z: -ROOM_HALF + 0.05 }, rotation: 0 }
        ]
    },
    {
        id: 4,
        name: 'Mystic Hall',
        wallColor: 0x6A8F5A,
        floorColor: 0x4A5A3A,
        ceilingColor: 0xE0F0E0,
        doorPosition: { x: -ROOM_HALF + 0.1, z: 0 },
        furniture: [
            { type: 'rug', position: { x: 0, y: 0, z: 0 }, size: 5 },
            { type: 'table', position: { x: 5, y: 0.5, z: 5 } },
            { type: 'table', position: { x: -5, y: 0.5, z: -5 } },
            { type: 'bookshelf', position: { x: -ROOM_HALF + 0.4, y: 1, z: -5 } },
            { type: 'bookshelf', position: { x: ROOM_HALF - 0.4, y: 1, z: 5 } },
            { type: 'bookshelf', position: { x: 0, y: 1, z: ROOM_HALF - 0.4 } },
            { type: 'chair', position: { x: 5, y: 0.4, z: 4 } },
            { type: 'chair', position: { x: -5, y: 0.4, z: -4 } },
            { type: 'chest', position: { x: 5, y: 0.3, z: -5 } },
            { type: 'chest', position: { x: -5, y: 0.3, z: 5 } },
            { type: 'pillar', position: { x: -6, y: 0.75, z: -6 } },
            { type: 'pillar', position: { x: 6, y: 0.75, z: 6 } },
            { type: 'pillar', position: { x: 6, y: 0.75, z: -6 } },
            { type: 'statue', position: { x: 0, y: 0, z: 6 } },
            { type: 'lamp', position: { x: 4, y: 0, z: -4 } },
            { type: 'lamp', position: { x: -4, y: 0, z: 4 } },
            { type: 'plant', position: { x: 7, y: 0, z: 0 } },
            { type: 'plant', position: { x: -7, y: 0, z: 0 } },
            { type: 'mirror', position: { x: 0, y: 1.5, z: ROOM_HALF - 0.05 }, rotation: 0 },
            { type: 'vase', position: { x: 5, y: 0.65, z: 5 } },
            { type: 'vase', position: { x: -5, y: 0.65, z: -5 } },
            { type: 'painting', position: { x: 0, y: 2, z: ROOM_HALF - 0.05 }, rotation: 0 },
            { type: 'painting', position: { x: 0, y: 2, z: -ROOM_HALF + 0.05 }, rotation: Math.PI },
            { type: 'clock', position: { x: -ROOM_HALF + 0.05, y: 2.5, z: 0 }, rotation: Math.PI / 2 }
        ]
    },
    {
        id: 5,
        name: 'Grand Finale',
        wallColor: 0x9F9F6B,
        floorColor: 0x6A6A4A,
        ceilingColor: 0xF5F5E8,
        doorPosition: { x: 0, z: -ROOM_HALF + 0.1 },
        furniture: [
            { type: 'rug', position: { x: 0, y: 0, z: 0 }, size: 6 },
            { type: 'table', position: { x: -5, y: 0.5, z: -5 } },
            { type: 'table', position: { x: 5, y: 0.5, z: -5 } },
            { type: 'table', position: { x: -5, y: 0.5, z: 5 } },
            { type: 'table', position: { x: 5, y: 0.5, z: 5 } },
            { type: 'bookshelf', position: { x: -ROOM_HALF + 0.4, y: 1, z: 0 } },
            { type: 'bookshelf', position: { x: ROOM_HALF - 0.4, y: 1, z: 0 } },
            { type: 'bookshelf', position: { x: 0, y: 1, z: -ROOM_HALF + 0.4 } },
            { type: 'bookshelf', position: { x: 0, y: 1, z: ROOM_HALF - 0.4 } },
            { type: 'chair', position: { x: -5, y: 0.4, z: -4 } },
            { type: 'chair', position: { x: 5, y: 0.4, z: -4 } },
            { type: 'chair', position: { x: -5, y: 0.4, z: 4 } },
            { type: 'chair', position: { x: 5, y: 0.4, z: 4 } },
            { type: 'chest', position: { x: 0, y: 0.3, z: 0 } },
            { type: 'pillar', position: { x: -6, y: 0.75, z: -6 } },
            { type: 'pillar', position: { x: 6, y: 0.75, z: -6 } },
            { type: 'pillar', position: { x: -6, y: 0.75, z: 6 } },
            { type: 'pillar', position: { x: 6, y: 0.75, z: 6 } },
            { type: 'statue', position: { x: -7, y: 0, z: -7 } },
            { type: 'statue', position: { x: 7, y: 0, z: 7 } },
            { type: 'statue', position: { x: 0, y: 0, z: 0 } },
            { type: 'lamp', position: { x: -3, y: 0, z: -3 } },
            { type: 'lamp', position: { x: 3, y: 0, z: 3 } },
            { type: 'lamp', position: { x: -3, y: 0, z: 3 } },
            { type: 'lamp', position: { x: 3, y: 0, z: -3 } },
            { type: 'plant', position: { x: 0, y: 0, z: 7 } },
            { type: 'plant', position: { x: 0, y: 0, z: -7 } },
            { type: 'vase', position: { x: -5, y: 0.65, z: -5 } },
            { type: 'vase', position: { x: 5, y: 0.65, z: -5 } },
            { type: 'vase', position: { x: -5, y: 0.65, z: 5 } },
            { type: 'vase', position: { x: 5, y: 0.65, z: 5 } },
            { type: 'painting', position: { x: -ROOM_HALF + 0.05, y: 2, z: 0 }, rotation: 0 },
            { type: 'painting', position: { x: ROOM_HALF - 0.05, y: 2, z: 0 }, rotation: Math.PI },
            { type: 'clock', position: { x: 0, y: 2.5, z: ROOM_HALF - 0.05 }, rotation: Math.PI }
        ]
    }
];